apiVersion: v1
kind: Template
metadata:
  name: shoppint-cart-template
  annotations:
    description: "shoppint-cart Template"
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: shoppint-cart
    spec:
      selector:
        matchLabels:
          app: shoppint-cart
      replicas: 1
      template:
        metadata:
          labels:
            app: shoppint-cart
        spec:
          containers:
            - name: shoppint-cart
              image: quay.io/${QUAY_USER_OR_GROUP}/${APP_IMAGE_NAME}:${APP_IMAGE_TAG}
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
      strategy:
        type: RollingUpdate
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: shoppint-cart
      name: shoppint-cart
    spec:
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: shoppint-cart
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: shoppint-cart
      labels:
        app: shoppint-cart
    spec:
      to:
        kind: Service
        name: shoppint-cart
      port:
        targetPort: 8080

parameters:
  - name: QUAY_USER_OR_GROUP
    description: "Quay User/Group"
    required: true
  - name: APP_IMAGE_NAME
    description: "Image Name"
    required: false
    value: "shoppint-cart"
  - name: APP_IMAGE_TAG
    description: "Image Tag"
    required: false
    value: "latest"
